# PyTorch Practice

In [ ]:
import torch

from torch import nn

## Create and manipulate tensor
1. `torch.zeros()`
2. `torch.Tensor.shape` vs `torch.Tensor.size()`
3. `torch.arange()`
4. `torch.Tensor.unsqueeze()` vs `torch.Tensor.view()`

In [23]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [24]:
x.shape, x.size()

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 1, 2, 1, 2]))

In [25]:
start = 0
end = 1
step = 0.02
squeezed_X = torch.arange(start, end, step)
squeezed_X.shape, squeezed_X

(torch.Size([50]),
 tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
         0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
         0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
         0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
         0.7200, 0.7400, 0.7600, 0.7800, 0.8000, 0.8200, 0.8400, 0.8600, 0.8800,
         0.9000, 0.9200, 0.9400, 0.9600, 0.9800]))

In [26]:
unsqueezed_X = squeezed_X.unsqueeze(dim=1)
unsqueezed_X.shape, unsqueezed_X

(torch.Size([50, 1]),
 tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800],
         [0.2000],
         [0.2200],
         [0.2400],
         [0.2600],
         [0.2800],
         [0.3000],
         [0.3200],
         [0.3400],
         [0.3600],
         [0.3800],
         [0.4000],
         [0.4200],
         [0.4400],
         [0.4600],
         [0.4800],
         [0.5000],
         [0.5200],
         [0.5400],
         [0.5600],
         [0.5800],
         [0.6000],
         [0.6200],
         [0.6400],
         [0.6600],
         [0.6800],
         [0.7000],
         [0.7200],
         [0.7400],
         [0.7600],
         [0.7800],
         [0.8000],
         [0.8200],
         [0.8400],
         [0.8600],
         [0.8800],
         [0.9000],
         [0.9200],
         [0.9400],
         [0.9600],
         [0.9800]]))

In [27]:
view_X = squeezed_X.view(-1, 1)
view_X.shape, view_X

(torch.Size([50, 1]),
 tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800],
         [0.2000],
         [0.2200],
         [0.2400],
         [0.2600],
         [0.2800],
         [0.3000],
         [0.3200],
         [0.3400],
         [0.3600],
         [0.3800],
         [0.4000],
         [0.4200],
         [0.4400],
         [0.4600],
         [0.4800],
         [0.5000],
         [0.5200],
         [0.5400],
         [0.5600],
         [0.5800],
         [0.6000],
         [0.6200],
         [0.6400],
         [0.6600],
         [0.6800],
         [0.7000],
         [0.7200],
         [0.7400],
         [0.7600],
         [0.7800],
         [0.8000],
         [0.8200],
         [0.8400],
         [0.8600],
         [0.8800],
         [0.9000],
         [0.9200],
         [0.9400],
         [0.9600],
         [0.9800]]))

## Gradient example

In [ ]:
import torch

from torch import nn

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

In [ ]:
y = x ** 2
y

In [ ]:
y.backward()

In [ ]:
x.grad

In [4]:
import torch

from torch import nn
from torch.utils.data import Dataset

In [14]:
class CreateData(Dataset):
    def __init__(self, start: int, end: int, step: int):
        
        self.x = torch.arange(start, end, step).view(-1, 1)
        # self.unsqueezed_X = self.x.unsqueeze(dim=1) # add extra dim
        self.y = -3 * self.x  + 1
        self.len = self.x.shape[0]

    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.len
    

In [15]:
start = -3
end = 3
step = 0.01
dataset = CreateData(start, end, step)
dataset

In [16]:
len(dataset)

600

In [17]:
x, y = dataset[0]

In [18]:
x

tensor([-3.])

In [19]:
y

tensor([10.])

In [20]:
x, y = dataset[:3]

In [21]:
x

tensor([[-3.0000],
        [-2.9900],
        [-2.9800]])

In [22]:
y

tensor([[10.0000],
        [ 9.9700],
        [ 9.9400]])